# Generated by Django 3.1.1 on 2022-01-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('please choose', 'please choose')], default='please choose', max_length=30, verbose_name='Menu Status'),
        ),
    ]
