# Generated by Django 3.1.1 on 2022-03-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Drop a message'},
        ),
    ]
