# Generated by Django 3.1.1 on 2022-01-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks_App', '0002_auto_20220117_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sylviaphotos',
            options={'verbose_name_plural': 'Sylvia-Photos'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('', 'please choose')], default='', max_length=30, verbose_name='Menu Status'),
        ),
    ]
