# Generated by Django 3.1.1 on 2022-01-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks_App', '0002_auto_20220114_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
