# Generated by Django 3.1.1 on 2022-01-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks_App', '0003_auto_20220114_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
