# Generated by Django 3.1.1 on 2022-01-21 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Snacks_App', '0003_auto_20220121_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_description',
            field=models.TextField(default='Creamy and yummy', verbose_name='Yummy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default='Cakes', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.CharField(default=7000, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='snacks_description',
            field=models.TextField(default='yummy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='snacks_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='sylvia_image1'),
        ),
        migrations.AddField(
            model_name='menu',
            name='snacks_name',
            field=models.CharField(default='cakes', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='snacks_price',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
