# Generated by Django 3.1.1 on 2022-01-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks_App', '0004_auto_20220121_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_price',
        ),
        migrations.AddField(
            model_name='homeslides',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sylviaphotos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-24'),
            preserve_default=False,
        ),
    ]
