# Generated by Django 3.1.1 on 2022-01-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Snacks_App', '0005_auto_20220124_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=2)),
                ('message', models.TextField()),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Snacks_App.menu')),
            ],
        ),
    ]
